'package: angular-query-devtools-experimental':
  - changed-files:
      - any-glob-to-any-file: 'packages/angular-query-devtools-experimental/**/*'
'package: angular-query-experimental':
  - changed-files:
      - any-glob-to-any-file: 'packages/angular-query-experimental/**/*'
'package: angular-query-persist-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/angular-query-persist-client/**/*'
'package: eslint-plugin-query':
  - changed-files:
      - any-glob-to-any-file: 'packages/eslint-plugin-query/**/*'
'package: query-async-storage-persister':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-async-storage-persister/**/*'
'package: query-broadcast-client-experimental':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-broadcast-client-experimental/**/*'
'package: query-codemods':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-codemods/**/*'
'package: query-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-core/**/*'
'package: query-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-devtools/**/*'
'package: query-persist-client-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-persist-client-core/**/*'
'package: query-sync-storage-persister':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-sync-storage-persister/**/*'
'package: query-test-utils':
  - changed-files:
      - any-glob-to-any-file: 'packages/query-test-utils/**/*'
'package: react-query':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-query/**/*'
'package: react-query-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-query-devtools/**/*'
'package: react-query-next-experimental':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-query-next-experimental/**/*'
'package: react-query-persist-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-query-persist-client/**/*'
'package: solid-query':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-query/**/*'
'package: solid-query-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-query-devtools/**/*'
'package: solid-query-persist-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-query-persist-client/**/*'
'package: svelte-query':
  - changed-files:
      - any-glob-to-any-file: 'packages/svelte-query/**/*'
'package: svelte-query-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/svelte-query-devtools/**/*'
'package: svelte-query-persist-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/svelte-query-persist-client/**/*'
'package: vue-query':
  - changed-files:
      - any-glob-to-any-file: 'packages/vue-query/**/*'
'package: vue-query-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/vue-query-devtools/**/*'
'documentation':
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
