packages:
  - 'packages/**'
  - 'integrations/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/svelte/**'
  - 'examples/vue/**'
  - 'examples/qwik/**'
  - '!examples/vue/2*'
  - '!examples/vue/nuxt*'
  - '!packages/react-query/build/**'
