name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [main, 'v[0-9]', '*-pre', '*-maint']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    name: autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Tools
        uses: TanStack/config/.github/setup@e4b48f16568324f76f467aa4c2aac2f05db632c3
      - name: Fix formatting
        run: pnpm run format
      - name: Apply fixes
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with:
          commit-message: 'ci: apply automated fixes'
