name: Labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: labeler-config.yml
